name: Simulator match

on:
  push:
    branches:
      - main
  pull_request: {}
  release:
    types: [ created ]

jobs:
  skip_duplicates:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  run-comp-match:
    needs: skip_duplicates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webots-version: ["2022b", "2023a"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: libraries.txt

      - name: Install Libraries
        run: |
          pip install -r libraries.txt

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install --yes wget zip pulseaudio xvfb
          pulseaudio -D

      - name: Download Webots
        run: |
          wget -O ./webots.deb \
          https://github.com/cyberbotics/webots/releases/download/R${{ matrix.webots-version }}/webots_${{ matrix.webots-version }}_amd64.deb

      - name: Install Webots
        run: |
          sudo apt-get install --yes ./webots.deb

      - name: Prepare team code archive
        run: |
          mkdir archives
          cd archives

          # Convert the sleep comments to print statement so there's a way to
          # gauge progress and so that GitHub doesn't shut things down due to
          # lack of output (the latter is a theoretical concern).
          sed -r 's/# sleep(.*)/print("sleep\1")/' ../controllers/example_controller/example_controller.py > robot.py

          # Have the robot code print success at the end, along with a unique identifier.
          echo "print('Success: $GITHUB_SHA')" >> robot.py

          zip ABC.zip robot.py

      - name: Hide overlays
        run: |
          # pre-run webots to generate the config file
          xvfb-run webots --sysinfo
          sed --in-place '
            s/\(hideAllCameraOverlays\)=.*/\1=true/
            s/\(hideAllDisplayOverlays\)=.*/\1=true/
            ' ~/.config/Cyberbotics/Webots-*.conf

      - name: Run match
        run: |
          xvfb-run script/run-comp-match archives 42 ABC --duration 5 --resolution 1280 720

      - name: Store archives
        uses: actions/upload-artifact@v2
        with:
          name: match-archives-${{ matrix.webots-version }}
          path: archives

      - name: Validate success of zone 0
        run: |
          LAST_LINE=$(tail --lines=1 archives/ABC/log-zone-0-match-42.txt)
          set -x
          test "$LAST_LINE" == "0| Success: $GITHUB_SHA"
