name: Simulator match

on:
  push:
    branches:
      - master
      - sb2021
  pull_request: {}
  release:
    types: [ created ]

jobs:
  skip_duplicates:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  run-comp-match:
    needs: skip_duplicates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webots-version: ['2021b']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get update
          sudo apt-get install --yes wget zip pulseaudio xvfb
          pulseaudio -D
      - name: Download Webots
        run: |
          wget -O ./webots.deb \
          https://github.com/cyberbotics/webots/releases/download/R${{ matrix.webots-version }}/webots_${{ matrix.webots-version }}_amd64.deb
      - name: Install Webots
        run: |
          sudo apt-get install --yes ./webots.deb
      - name: Prepare team code archives
        run: |
          mkdir archives
          cd archives

          # Convert the sleep comments to print statement so there's a way to
          # gauge progress and so that GitHub doesn't shut things down due to
          # lack of output (the latter is a theoretical concern).
          sed -r 's/# sleep(.*)/print("sleep\1")/' ../controllers/example_controller/example_forklift.py > forklift.py
          sed -r 's/# sleep(.*)/print("sleep\1")/' ../controllers/example_controller/example_crane.py > crane.py

          # Have the robot code print success at the end, along with a unique identifier.
          echo "print('Success: $GITHUB_SHA')" >> forklift.py
          echo "print('Success: $GITHUB_SHA')" >> crane.py

          zip ABC.zip forklift.py crane.py

          # Make a second team to compete against
          cp ABC.zip DEF.zip
      - name: Cache libraries
        id: cache-library
        uses: actions/cache@v2
        with:
          path: venv
          key: deps-library-${{ hashfiles('libraries.txt') }}-v3
      - name: Install Libraries
        run: |
          python3 -m venv venv
          venv/bin/pip install -U pip
          venv/bin/pip install -r libraries.txt
      - name: Hide overlays
        run: |
          # pre-run webots to generate the config file
          xvfb-run webots --sysinfo
          sed --in-place '
            s/\(hideAllCameraOverlays\)=.*/\1=true/
            s/\(hideAllDisplayOverlays\)=.*/\1=true/
            ' ~/.config/Cyberbotics/Webots-*.conf
      - name: Run match
        run: |
          source ./venv/bin/activate
          xvfb-run script/run-comp-match archives 42 ABC DEF --duration 5 --resolution 1280 720
      - name: Store archives
        uses: actions/upload-artifact@v2
        with:
          name: match-archives-${{ matrix.webots-version }}
          path: archives
      - name: Validate success zone 0 forklift
        run: |
          LAST_LINE=$(tail --lines=1 archives/ABC/log-zone-0-forklift-match-42.txt)
          set -x
          test "$LAST_LINE" == "0 forklift| Success: $GITHUB_SHA"
      - name: Validate success zone 0 crane
        run: |
          LAST_LINE=$(tail --lines=1 archives/ABC/log-zone-0-crane-match-42.txt)
          set -x
          test "$LAST_LINE" == "0 crane| Success: $GITHUB_SHA"
      - name: Validate success zone 1 forklift
        run: |
          LAST_LINE=$(tail --lines=1 archives/DEF/log-zone-1-forklift-match-42.txt)
          set -x
          test "$LAST_LINE" == "1 forklift| Success: $GITHUB_SHA"
      - name: Validate success zone 1 crane
        run: |
          LAST_LINE=$(tail --lines=1 archives/DEF/log-zone-1-crane-match-42.txt)
          set -x
          test "$LAST_LINE" == "1 crane| Success: $GITHUB_SHA"
